triton-lang/triton-cpu

include/triton/Conversion/TritonCPUToLLVM/CPUTargetInfo.h, include/triton/Conversion/TritonCPUToLLVM/PatternTritonCPUOpToLLVM.h, include/triton/Conversion/TritonCPUToLLVM/Utility.h, lib/Conversion/TritonCPUToLLVM/CMakeLists.txt, lib/Conversion/TritonCPUToLLVM/CPUTargetInfo.cpp, lib/Conversion/TritonCPUToLLVM/PrintOpToLLVM.cpp, lib/Conversion/TritonCPUToLLVM/SPMDOpToLLVM.cpp, lib/Conversion/TritonCPUToLLVM/TritonCPUToLLVM.cpp, python/triton/runtime/jit.py
Summary: `tl.program_id` needs to be lowered first for any meaningful example. As of now, we think pid will be provided as additional function arguments to the kernel. The CPU launch (parallel for) will give grid ids. Getting program_id is mapped to reading one of the last three arguments.
I also quickly implemented `tl.device_print` or `print`, only for scalar types for a quick "Hello, World!" testing.
Test Plan: Tested with a simple example:
```
@triton.jit
def add_kernel(...):
pid = tl.program_id(axis=0)  # We use a 1D launch grid so axis is 0.
foo = pid + 42
tl.device_print("Hello, World!", foo, pid)
```
The resulting .llir is valid:
```
@printfFormat_1 = internal constant [31 x i8] c"pid (%u, %u, %u) test: %u, %u\0A\00"
declare !dbg !3 i32 @printf(ptr, ...)
define void …
```
=> [BACKEND][CPU] Convert tt.get_program_id and tt.print (Hello World)

lib/Conversion/TritonCPUToLLVM/PrintOpToLLVM.cpp, lib/Conversion/TritonCPUToLLVM/TypeConverter.cpp, lib/Conversion/TritonToTritonCPU/TritonCPUConversion.cpp, python/triton/runtime/jit.py, third_party/cpu/backend/compiler.py, third_party/cpu/backend/driver.py
Okay, before merging with Ilya's changes, let's still make the current tree be compilable after the rebasing.
=> Quick patches to make it work after rebasing

python/test/unit/language/test_core.py
The recent LLVM update broke one of the FP cast tests. This is a temporary workaround.
=> Add a workaround for LLVM bug in codegen for bf16 vector cast.

include/triton/Conversion/CMakeLists.txt, lib/Conversion/CMakeLists.txt, python/src/passes.cc, python/triton/runtime/build.py, third_party/cpu/backend/compiler.py, third_party/cpu/backend/driver.py, third_party/cpu/include/TritonCPUToLLVM/CMakeLists.txt
For some reasons, my environment (Centos 9) needs some quick fixes to make the current triton-cpu buildable and runnable.
Build:
```
DEBUG=1 LLVM_INCLUDE_DIRS=$LLVM_BUILD_DIR/include LLVM_LIBRARY_DIR=$LLVM_BUILD_DIR/lib LLVM_SYSPATH=$LLVM_BUILD_DIR pip install -e python 
```
Running a tutorial (you need to fix the tutorial though, which I will commit as well):
```
TRITON_CPU_BACKEND=1 python3 python/tutorials/01-vector-add.py
```
=> [BACKEND][CPU] Make it buildable and runnable in a different environment

python/test/unit/language/test_core.py, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonCPUToLLVM/Passes.h, third_party/cpu/include/TritonCPUToLLVM/Passes.td, third_party/cpu/include/TritonToTritonCPU/Passes.h, third_party/cpu/include/TritonToTritonCPU/Passes.td, third_party/cpu/lib/TritonCPUToLLVM/CMakeLists.txt, third_party/cpu/lib/TritonCPUToLLVM/LowerMultiReduction.cpp, third_party/cpu/lib/TritonToTritonCPU/CMakeLists.txt, third_party/cpu/lib/TritonToTritonCPU/ConvertReductionOp.cpp, third_party/cpu/lib/TritonToTritonCPU/Pipeline.cpp, third_party/cpu/triton_cpu.cc
This covers only those cases that are covered by `vector::MultiDimReductionOp`. Generic case support will have to be added later.
=> Add support for simple reductions.

python/test/unit/language/test_core.py, third_party/cpu/include/TritonToTritonCPU/Passes.h, third_party/cpu/include/TritonToTritonCPU/Passes.td, third_party/cpu/lib/TritonToTritonCPU/CMakeLists.txt, third_party/cpu/lib/TritonToTritonCPU/ConvertHistogramOp.cpp, third_party/cpu/lib/TritonToTritonCPU/Pipeline.cpp
Each histogram bin is just a single value, so the implementation compares each input value with a target range and sums all comparison results.
=> Support tl.histogram for CPU.

third_party/cpu/include/TritonToTritonCPU/Passes.td, third_party/cpu/lib/TritonToTritonCPU/ConvertReductionOp.cpp
My bad. I won't resolve merge conflicts in the github editor directly. 
And I fixed/updated some code in `buildInitValue`. See the inlined comments.
=> Fix merge error and compile error and bugs in buildInitValue

python/triton/backends/__init__.py, python/triton/backends/driver.py, python/triton/runtime/driver.py, python/triton/runtime/jit.py, python/triton/testing.py, python/tutorials/01-vector-add.py
As the title, this PR runs both CPU and GPU in the vector-add.py tutorial. Note that we didn't yet have an OpenMP based parallelism, so the perf is super slow. But it measures both CPU and GPU.
To change the active driver, I also needed to patch some code.
```
> % python3 python/tutorials/01-vector-add.py
tensor([1.3713, 1.3076, 0.4940,  ..., 0.6724, 1.2141, 0.9733], device='cuda:0')
tensor([1.3713, 1.3076, 0.4940,  ..., 0.6724, 1.2141, 0.9733], device='cuda:0')
The maximum difference between torch and triton is 0.0
tensor([1.3713, 1.3076, 0.4940,  ..., 0.6724, 1.2141, 0.9733])
The maximum difference between torch and triton-cpu is 0.0
vector-add-performance (BLOCK_SIZE=1024):
size  TritonCPU       Triton        Torch
0        4096.0   0.495005    11.548873    11.050360
1        8192.0 …
```
=> [CPU] Support flexible active driver + update vector-add tutorial

.github/workflows/build-test.yml
This workflow now is able to execute tests, some of them still fail but many tests pass.
=> Fixed build and test workflow for intel self-hosted runner

include/triton/Tools/Sys/GetEnv.hpp, python/triton/runtime/build.py, python/tutorials/01-vector-add.py, third_party/cpu/backend/driver.py
This PR implements a simple OpenMP-based CPU launcher with some debugging and tunable environment variables. 
**Details:**
- By default, it uses the entire threads on a machine. So there might be a chance of contention between logical threads on the same physical core. Need a fine tuning.
- It uses static scheduling. No reason to use dynamic scheduling for now (overhead is high). I used the default chunk size: total iterations / # of threads, where the minimum chunk size is 10.
**Initial performance:**
Environment: I only tested on an AMD EPYC Zen4 96-core machine with Centos 9, as a development server in Meta. My test wasn't on a physical machine; it is a VM.
I only tested the vector addition example. I added `TritonCPU 1-core` as well as `TorchCPU` as the references. I disabled the …
=> [CPU] Add an OpenMP-based CPU launcher

python/triton/compiler/compiler.py, third_party/cpu/backend/compiler.py
I think it'd be much better to dump generated assembly code in the cache directory.
`.asm` file is now dropped at `TRITON_CACHE_DIR`.
```
> % ll /home/minjang/temp/triton-cache/888bdd8e7af20d785cf333479fbae3dd400aca0d11d7ceec5739759a8b2da4b2/
total 276
-rw-r--r-- 1 minjang users 169178 Jun 10 15:27 add_kernel.asm
-rw-r--r-- 1 minjang users  10724 Jun 10 15:27 add_kernel.bc
-rw-r--r-- 1 minjang users    394 Jun 10 15:27 add_kernel.json
-rw-r--r-- 1 minjang users  43591 Jun 10 15:27 add_kernel.llir
-rw-r--r-- 1 minjang users  37239 Jun 10 15:27 add_kernel.ttcir
-rw-r--r-- 1 minjang users   3418 Jun 10 15:27 add_kernel.ttir
-rw-r--r-- 1 minjang users    823 Jun 10 15:27 __grp__add_kernel.json
```
=> [CPU] Dump human-readable asm code in TRITON_CACHE_DIR

.github/workflows/build-test.yml
After switching runner from `summerwind/actions-runner:ubuntu-20.04` to `summerwind/actions-runner:ubuntu-22.04` we need to install g++ in the container because it is no longer present in it.
=> Added g++ installation after switching to ubuntu-22.04

third_party/cpu/include/TritonToTritonCPU/Passes.h, third_party/cpu/include/TritonToTritonCPU/Passes.td, third_party/cpu/lib/TritonToTritonCPU/CMakeLists.txt, third_party/cpu/lib/TritonToTritonCPU/ConvertElemManipOps.cpp, third_party/cpu/lib/TritonToTritonCPU/ConvertElementwiseOps.cpp, third_party/cpu/lib/TritonToTritonCPU/Pipeline.cpp
We have many operation conversions in `ConvertElementwiseOps` pass and some of them are not actually elementeise. It started with a single pattern because it was not reasonable to introduce a new pass for it, but more and more operations were added later. This patch moves those patterns into a new pass that covers vector element manipulations, like shuffles, broadcasts, etc. This is pure refactoring, with no functional changes
=> Move byte manipulation ops from elwise ops conversion.

python/tutorials/01-vector-add.py, python/tutorials/02-fused-softmax-cpu.py, python/tutorials/03-matrix-multiplication-cpu.py
The updated fused-softmax has only persistent thread approach, which isn't straightforward for CPU. So, at least for now, bring back the old version and make it for CPU.
```
> % python3 python/tutorials/02-fused-softmax-cpu.py
softmax-performance:
N  TritonCPU 1  TritonCPU  TorchCPU (native)  TorchCPU (jit)    TritonGPU  TorchGPU (native)  TorchGPU (jit)
0    256.0     2.045810   0.542863           0.550007        0.105642   923.042225         907.072700      289.023160
1    384.0     1.427173   0.807165           0.810944        0.177129  1110.779696        1095.309199      366.122895
2    512.0     1.784980   1.068528           1.088198        0.211705  1297.742602        1263.344616      429.744271
3    640.0     1.041241   1.301883           1.346970        0.262986  1489.454534 …
```
=> [TUTORIAL] Add the non-persistent softmax and make it for CPU

python/test/unit/language/test_core.py
With our new compilation flow, we now respect the `enable_fp_fusion` option and can scan the resulting assembly code in tests.
=> Enable few more core tests for CPU.

python/triton/runtime/build.py, third_party/cpu/backend/driver.py
Make triton-cpu buildable and runnable on Mac M1, use llvm-config to locate the llvm headers and libraries.
=> [CPU]Mac build for triton-cpu

.github/workflows/build-test.yml, .github/workflows/integration-tests.yml, .github/workflows/integration-tests.yml.in
The core Triton is a small number of people, and we receive many PRs (thank
you!).  To help us review your code more quickly, **if you are a new
contributor (less than 3 PRs merged) we ask that you complete the following
tasks and include the filled-out checklist in your PR description.**
Complete the following tasks before sending your PR, and replace `[ ]` with
`[x]` to indicate you have done them.
- Select one of the following.
- `/test` for `lit` tests
- `/unittest` for C++ tests
- `/python/test` for end-to-end tests
- Select one of the following.
including the "tests should be minimal" section. (Usually running Python code
and using the instructions it generates is not minimal.)
=> Enabled simple build&test workflow, disabled old Integration Tests workflow because it fails to run

python/test/unit/language/test_core.py, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonCPUTransforms/Passes.h, third_party/cpu/include/TritonCPUTransforms/Passes.td, third_party/cpu/lib/TritonCPUTransforms/ConvertUnsupportedOps.cpp, third_party/cpu/triton_cpu.cc
This allows us to run most of test_dot variations on CPU. Those are quite slow though because run in a single thread, so I reduced input sizes for CPU.
=> Add conversions for mixed precision matmuls.

python/test/unit/language/test_core.py, third_party/cpu/backend/driver.py, third_party/cpu/include/TritonCPUToLLVM/Passes.td, third_party/cpu/lib/TritonCPUToLLVM/FuncOpToLLVM.cpp, third_party/cpu/lib/TritonCPUToLLVM/GetProgramIdOpToLLVM.cpp
This commit supports 'get_num_programs' in a same way with 'get_program_id'.
Verified with pytest: "test_core.py::test_num_programs"
- Select one of the following.
- `/test` for `lit` tests
- `/unittest` for C++ tests
- `/python/test` for end-to-end tests
- Select one of the following.
including the "tests should be minimal" section. (Usually running Python code
and using the instructions it generates is not minimal.)
=> [Op support] Support 'get_num_programs'

python/src/llvm.cc, third_party/cpu/backend/compiler.py, third_party/cpu/triton_cpu.cc
Add fast-math option: allow unsafe fp math optimizations and reassociation.
=> Add fast-math support

third_party/cpu/backend/compiler.py, third_party/cpu/backend/driver.py
... instead of doing it at load time. This more closely mirrors how the other backends work. E.g. for the CUDA backend, we compile ptx -> cubin as part of staged lowering too.
=> [so] Compile asm to .so as part of staged lowering

python/test/unit/language/test_core.py, third_party/cpu/lib/TritonToTritonCPU/ConvertDotOp.cpp
This commit adds implementation for 3 dimensional dot operation.
=> [Op support] Dot3D support

.github/workflows/build-test.yml, python/test/unit/language/test_conversions.py, python/test/unit/language/test_core.py, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonCPUTransforms/Passes.h, third_party/cpu/include/TritonCPUTransforms/Passes.td, third_party/cpu/lib/TritonCPUTransforms/DecomposeFpConversions.cpp, third_party/cpu/lib/TritonCPUTransforms/OptCommon.h, third_party/cpu/lib/TritonToTritonCPU/ConvertElementwiseOps.cpp, third_party/cpu/triton_cpu.cc
This PR adds FP8 conversions so that we can run appropriate tests. Efficient conversions are used only in a couple of cases, others follow a generic emulation similar to the one used in conversion tests.
=> Support FP8 conversions for CPU.

third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonCPUToLLVM/Passes.h, third_party/cpu/include/TritonCPUToLLVM/Passes.td, third_party/cpu/lib/TritonCPUToLLVM/CMakeLists.txt, third_party/cpu/lib/TritonCPUToLLVM/DebugOpsToLLVM.cpp, third_party/cpu/lib/TritonCPUToLLVM/GetProgramIdOpToLLVM.cpp, third_party/cpu/lib/TritonCPUToLLVM/Pipeline.cpp, third_party/cpu/lib/TritonCPUToLLVM/Utility.cpp, third_party/cpu/lib/TritonCPUToLLVM/Utility.h, third_party/cpu/triton_cpu.cc
As title, I'm adding device_print support. But for some reasons, printing tensors needed more work. So I'm firstly publishing the support for scalars. A minor refactoring is included.
---
`device_print` has an interesting behavior for GPU. Each thread prints its own scalar elements for a tensor. For CPUs including the interpreter, we can literally print tensors as is.
A quick testing:
```
def add_kernel(...)
pid = tl.program_id(axis=0)  # We use a 1D launch grid so axis is 0.
block_start = pid * BLOCK_SIZE
offsets = block_start + tl.arange(0, BLOCK_SIZE)
mask = offsets < n_elements
x = tl.load(x_ptr + offsets, mask=mask)
y = tl.load(y_ptr + offsets, mask=mask)
output = x + y
tl.device_print("test", n_elements, BLOCK_SIZE, pid)
tl.store(output_ptr + offsets, output, mask=mask)
``` …
=> [CPU] Support device_print for scalar types

python/test/unit/language/test_core.py, third_party/cpu/lib/TritonToTritonCPU/ConvertControlFlowOps.cpp
This commit copies same approach as it were for `scf::for`. It's aimed to convert types like: `tensor<32xi32>` to `vector<32xi32>`.
Maybe there should be some utility that will be used in all such ConversionPasses to avoid code-duplication.
=> [Scf If types] Support conversion of types for scf::if

python/test/unit/language/test_core.py
This commit replaces torch.matmul for fp16 cpu case with np.matmul. As there is no implementation for such configuration.
- `test_dot_without_load`, 
- `test_masked_load_shared_memory`, 
- `test_tl_range` 
- skips `test_fp8_dot_acc` 
from `test_core` pytest suit.
=> [WA for fp16 torch.matmul] Replace torch.matmul with np.matmul

python/test/unit/language/test_core.py, third_party/cpu/lib/TritonCPUTransforms/ConvertUnsupportedOps.cpp
This commit enables several fp8 tests, that uses `tl.range`. Requires PR #40. 
Complete the following tasks before sending your PR, and replace `[ ]` with
`[x]` to indicate you have done them.
=> [FP8 tests] Enable several fp8 tests

python/triton/runtime/build.py
macOS gcc supports `-rpath` directly in the compilation driver, but on Linux we need to pass it directly to the linker. Fortunately this works on macOS too.
=> [cpu] Make runtime library build on Linux too

third_party/cpu/backend/driver.py
This commit resolves issue, that occurs on main 'pytest run'.
```
_triton_C_dir = importlib.resources.files(triton._C).joinpath("")
E   AttributeError: module 'importlib' has no attribute 'resources'
```
=> [FIX Pytest] Resolve 'importlib' issue

third_party/cpu/backend/driver.py
The previous implementation worked on Python 3.11 but had a host of issues with other versions. It boiled down to `triton._C` not being a regular package -- it doesn't have an `__init__.py` file. However, it can still be imported as a [namespace package][1]. Namespace packages can map to multiple locations on the filesystem, so we cannot get a path to the package contents without materializing the package.
The solution is to look up the files of the top-level `triton` package instead, which is a regular package, and use that to find the location of the `_C` directory.
I've tested that this approach works on 3.9 and 3.12 in macOS.
Fixes #76.
[1]: https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages
=> Fix importlib issues

.github/workflows/build-test.yml, third_party/cpu/backend/driver.py
The only test that needed fixing was `test_unknown_annotations`, where we were generating invalid code for the launcher. In particular, when `kernel_fn_args` was empty, we would get the following error:
```
/var/folders/_z/88s630fd3d9fx72mbmx90qvw0000gn/T/tmpy481mz0l/main.cpp:37:29: error: expected ';' before '(' token
37 | using kernel_ptr_t = void(*)(, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);
|                             ^
|                             ;
```
=> [cpu] Add test_annotations.py to CI

.github/workflows/build-test.yml, test/TritonCPU/reduction.mlir, third_party/cpu/lib/TritonToTritonCPU/ConvertReductionOp.cpp, third_party/cpu/lib/TritonToTritonCPU/ConvertScanOp.cpp, third_party/cpu/lib/TritonToTritonCPU/ReduceScanCommon.h
This results in the following compile-time assertion error (in debug Triton builds):
Assertion `Index < size() && "invalid index for value range"' failed.
This occurs when there is more than one tt.reduce call with a given
number of arguments in the same function, with the later call using more
arguments. Reusing the dummy values means that the subsequent call has
fewer dummy values than expected, hence the error.
This bug also resulted in type mismatches errors between the reused
dummy value and the current input value.
=> [cpu] Don't reuse shuffle dummies

.github/workflows/build-test.yml, python/setup.py, python/test/unit/cpu/test_libmvec.py, python/triton/language/extra/__init__.py, python/triton/language/extra/cpu/libdevice.py, third_party/cpu/backend/compiler.py, third_party/cpu/backend/driver.py, third_party/cpu/include/TritonCPUToLLVM/Passes.h, third_party/cpu/include/TritonCPUToLLVM/Passes.td, third_party/cpu/include/TritonCPUTransforms/Passes.h, third_party/cpu/include/TritonCPUTransforms/Passes.td, third_party/cpu/lib/TritonCPUToLLVM/CMakeLists.txt, third_party/cpu/lib/TritonCPUToLLVM/MathToLibmvec.cpp, third_party/cpu/lib/TritonCPUTransforms/ConvertUnsupportedOps.cpp, third_party/cpu/triton_cpu.cc
This patch adds a pass similar to math_to_libm_calls but using libmvec functions (libmvec is a part of libm added for OpenMP 4.0: https://sourceware.org/glibc/wiki/libmvec).
=> Utilize vector math functions from libmvec.

test/TritonCPU/convert-masked.mlir, third_party/cpu/lib/TritonToTritonCPU/ConvertMemoryOps.cpp
Doing so is likely to break invariants that the scf dialect expects. In particular, when handling a masked load or store within a scf.for loop, ConvertMemoryOps would create multiple blocks within that loop, resulting in errors of the form
'scf.for' op expects region #0 to have 0 or 1 blocks
I have added a test to exercise the `lowerToScalar{Loads,Stores}` codepaths. I have not included the for loop in those tests because I have already removed "cf" as a legal dialect for the ConvertMemoryOps pass, which should prevent future errors.
=> ConvertMemoryOps should not use cf dialect

python/test/unit/language/test_core.py, third_party/cpu/lib/TritonToTritonCPU/ConvertAtomicOps.cpp
We were previously discarding the original value & returning all zeros.
=> atomic_rmw ops should return original value

.github/workflows/build-test.yml, python/test/unit/cpu/test_opt.py, test/TritonCPU/convert-memory-ops.mlir, third_party/cpu/lib/TritonToTritonCPU/ConvertMemoryOps.cpp
Currently, if we detect a vector load/store, we extract a pointer from a tensor, then use it to build a memref, then make a load/store. The original tensor of pointers computation stays intact, and LLVM is not always capable of optimizing it to a scalar code. As a result, we might get a vector of pointers computations to just extract a single pointer from it to make a load.
This patch tries to rebuild a scalar pointer by going through the original tensor's data flow. This showed a nice improvement for softmax.
=> Compute a scalar pointer for vector load instead of extracting it from a tensor

python/test/unit/cpu/test_opt.py, test/TritonCPU/optimize-masks.mlir, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonCPUTransforms/Passes.h, third_party/cpu/include/TritonCPUTransforms/Passes.td, third_party/cpu/lib/TritonCPUTransforms/CMakeLists.txt, third_party/cpu/lib/TritonCPUTransforms/OptimizeMasks.cpp, third_party/cpu/triton_cpu.cc
This patch adds a few patterns that can optimize out masks in a typical tiled loop of the following form:
```
for i in range(0, tl.cdiv(size, TILE_SIZE)):
offs = i * TILE_SIZE + tl.arange(0, TILE_SIZE)
mask = offs < size
val = tl.load(in_ptr + offs, mask=mask, other=0)
res = ...
tl.sotre(out_ptr + offs, res, mask=mask)
```
given a hint that `size` is divisible by `TILE_SIZE`. The first couple of patterns try to remove the cdiv-mul pair and transform the loop into something like:
```
for i in range(0, size, TILE_SIZE):
offs = i + tl.arange(0, TILE_SIZE)
mask = offs < size
val = tl.load(in_ptr + offs, mask=mask, other=0)
res = ...
tl.sotre(out_ptr + offs, res, mask=mask)
```
The last one tries to prove that the maximum possible value of `offs` is always less than `size`. If `size` is …
=> Add pass to optimize masked loads and stores.

third_party/cpu/backend/compiler.py
I'm not sure we should provide a way to disable fast-math at all. The usage of vector operations is a foundation of the CPU backend and those are not allowed for strict math.
=> Enable fast-math by default.

python/test/unit/cpu/test_libdevice.py, third_party/cpu/lib/TritonCPUTransforms/ConvertUnsupportedOps.cpp, third_party/cpu/lib/TritonCPUTransforms/DecomposeFpConversions.cpp
This adds BF16 conversion for rsqrt call. I also had to decompose Fp32->Bf16 conversion because otherwise, LLVM optimizes
extf + floor into floor + extf.
=> Enable rsqrt and floor for BF16.

python/triton/runtime/build.py
There were a few reports with assembly file build error during TritonCPU usage:
```
/tmp/tmpvo4arrkd/kernel.s:4363: Error: junk at end of line, first unrecognized character is `"'
```
I don't have a confirmation of a root cause and couldn't reproduce the issue, but my suspicion is that a toolchain with no dwarf5 support is used and our `-gdwarf-5` option doesn't work. I realized that we don't have to specify a dwarf version and can simply use `-g`. So hopefully it will fix the issue.
=> Remove specific dwarf version from -g option.

python/triton/testing.py, python/tutorials/01-vector-add.py, python/tutorials/02-fused-softmax-cpu.py, python/tutorials/03-matrix-multiplication-cpu.py, python/tutorials/matrix-vector-multiplication-bf16.py, python/tutorials/matrix-vector-multiplication.py
Use `device_type` arg in `do_bench` instead of `is_cpu` arg added for CPU runs.
=> Remove is_cpu arg from do_bench.

.github/workflows/build-test.yml, python/triton/runtime/autotuner.py
Use the active driver to pass device type to do_bench in autotuner. This makes all tests in `test_autotuner.py` pass for CPU.
=> Pass device type to do_bench in autotuner.

python/test/unit/language/test_block_pointer.py, third_party/cpu/lib/TritonCPUToLLVM/MemoryOpToLLVM.cpp
There is a bug in indices extraction from block pointers. Indices are scaled by strides which is not required and it's a part of old code left from those times when indices and strides were used to compute an offset for memref. This bug causes a segfault in the fused attention tutorial.
=> Fix indices extraction from block pointer.

include/triton/Dialect/TritonCPU/IR/TritonCPUOps.td, include/triton/Dialect/TritonCPU/IR/TritonCPUTypes.td, lib/Dialect/TritonCPU/IR/CMakeLists.txt, lib/Dialect/TritonCPU/IR/Dialect.cpp, lib/Dialect/TritonCPU/IR/Ops.cpp, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonToTritonCPU/Passes.h, third_party/cpu/include/TritonToTritonCPU/Passes.td, third_party/cpu/lib/TritonCPUToLLVM/DebugOpsToLLVM.cpp, third_party/cpu/lib/TritonCPUToLLVM/TypeConverter.cpp, third_party/cpu/lib/TritonCPUToLLVM/TypeConverter.h, third_party/cpu/lib/TritonCPUTransforms/OptimizeMasks.cpp, third_party/cpu/lib/TritonToTritonCPU/CMakeLists.txt, third_party/cpu/lib/TritonToTritonCPU/ConvertDebugOps.cpp, third_party/cpu/runtime/cpu_runtime.cpp, third_party/cpu/triton_cpu.cc
Based on the discussions in [the previous PR](https://github.com/triton-lang/triton-cpu/pull/74), we don't explicitly want to have tensor types in TTCIR. So, this is a rework for the device_print with a simple 1D vector printing.
Sorry for a big PR but the printing code in `cpu_runtime.cpp` is isolated.
Some design considerations:
- Have the similar behavior like the interpreter.
- I decided to have `triton_cpu.print` for a couple of reasons: 
- `tt.print` prints pids as a prefix, but this pid is available in `TritonCPUtoLLVM`. It's not a good idea to move `FuncOpToLLVM.cpp`.
- We can't also simply keep `tt.print` by only updating the tensor operand types to vectors. `tt.print` accepts `TT_Type`, where vector type isn't specified. We shouldn't change the TTIR semantic here. So, having a …
=> [cpu] Rework device_print with triton_cpu.print and 1D vector printing

.github/workflows/build-test.yml, python/test/unit/language/test_pipeliner.py, python/test/unit/language/test_standard.py, python/test/unit/runtime/test_cache.py, python/test/unit/runtime/test_launch.py, python/triton/runtime/jit.py
This commits adds to testing several of already working suits.
I've enabled several pytests.
=> [Pytests] Add several suits

python/test/unit/language/test_core.py, test/TritonCPU/convert-memory-ops.mlir, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonToTritonCPU/Passes.h, third_party/cpu/include/TritonToTritonCPU/Passes.td, third_party/cpu/lib/TritonCPUTransforms/ConvertUnsupportedOps.cpp, third_party/cpu/lib/TritonToTritonCPU/ConvertMemoryOps.cpp, third_party/cpu/triton_cpu.cc
Currently, if we cannot detect contiguous memory access, we generate a sequence of scalar operations. In some cases, it might produce a lot of codes and cause a really long compilation. E.g. we use reduced input size in `test_permute` because of this problem.
This patch adds an option to generate scalar loops for such loads and stores. It helps to significantly reduce compilation time for scalarized loads/stores for big tensor sizes. We can now run the permute test with the original input size in a few seconds compared to several minutes when loops are not used.
Here is a store loop generated for perm_test:
```
%alloca = memref.alloca() {alignment = 64 : i64} : memref<128x128xf32> loc(#loc4)
vector.transfer_write %765, %alloca[%c0, %c0] {in_bounds = [true, true]} : vector<128x128xf32>, …
```
=> Add load/store scalarization through loops.

third_party/cpu/lib/TritonToTritonCPU/ConvertMemoryOps.cpp
clang++ seems more restrictive on this implicit casting to bool.
=> [cpu][easy] Fix compiler error on clang

test/TritonCPU/optimize-masks.mlir, third_party/cpu/backend/compiler.py, third_party/cpu/lib/TritonCPUTransforms/OptimizeMasks.cpp
This is a minor refactoring of the masks optimization. Instead of replacing masked load and stores having a mask proven to be all-ones, we replace such a mask with a constant and then let the canonicalizer do the rest. This allows additional benefits because such masks can be used in operations other than masked loads and stores. E.g. in the layer norm tutorial, this allows us to optimize out `arith.select` operation.
=> Offload a part of masks optimization to the canonicalizer.

python/test/unit/runtime/test_cache.py
This fixes the test failure introduced by the rebase upon upstream.
=> Make test_hooks CPU-compatible by using get_device_key

third_party/cpu/backend/driver.py
The version compatibility pain continues...
PyTorch still supports 3.8 so we need this
=> Make CPU runtime lib lookup work for Python 3.8

python/test/unit/cpu/test_libdevice.py, python/triton/language/core.py, python/triton/language/extra/cpu/__init__.py, python/triton/language/extra/cpu/libdevice.py
Since these aren't natively available in sleef / libmvec, let's implement them natively in Triton.
They were implemented via a `@builtin` wrapping a `@jit` function because operations like `get_int_dtype` don't work under `@jit`. The `@builtin` annotation was necessary so that we would get a handle to the `_generator`, which we can then use to call a JitFunction from a non-JIT one without specifying the grid.
=> Implement isnan, isinf, signbit

third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonCPUToLLVM/Passes.h, third_party/cpu/include/TritonCPUToLLVM/Passes.td, third_party/cpu/lib/TritonCPUToLLVM/CMakeLists.txt, third_party/cpu/lib/TritonCPUToLLVM/MathToVecLib.cpp, third_party/cpu/triton_cpu.cc
Since the pass can generate libsleef calls too, having "libmvec" in the pass name is a bit of a misnomer, so I've renamed it accordingly.
I've also switched from using a bool to using an enum to select between vector math libraries. This makes for cleaner code and makes it easy to extend to support additional libraries (e.g. MKL).
Finally (and most significantly), I've changed how library function names are generated. Instead of having all the logic in the MathToLibmvecPass, I'm giving each library its own naming functor. This makes it easier to extend to accomodate each library's quirks, as following PRs will demonstrate.
=> Refactor MathToLibmvec pass

test/TritonCPU/optimize-masks.mlir, third_party/cpu/lib/TritonCPUTransforms/OptimizeMasks.cpp
One of our optimization patterns can create a new operation and then return failure. In this case, added operation still stays and then is optimized out as a dead one. But this leads to a new cycle of pattern matching, produces another unused operation, etc. Fix it by avoiding a dead operation as a result of the pattern match.
=> Fix infinite optimization loop for mask optimization.

python/test/unit/language/test_core.py
With updated LLVM we don't need the old workaround anymore.
=> Remove old LLVM bug workaround.

python/test/unit/language/test_core.py
This commit enables dot3d test and skips float16->flooat16 cases. In this cases compilation is a too long and accuracy lower than it expected in test case.
=> [Dot3D test] Enable with lower block size

third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonToTritonCPU/Passes.h, third_party/cpu/include/TritonToTritonCPU/Passes.td, third_party/cpu/lib/TritonToTritonCPU/ConvertReductionOp.cpp, third_party/cpu/triton_cpu.cc
I found that the default reduction lowering we use right now doesn't provide the best performance. It utilizes `llvm.vector.reduce.*` intrinsics and those can be lowered to a scalar code. So, instead of using it, we might always rely on our generic reduction lowering. It showed better results in my softmax measurements. I still leave an option to use LLVM lowering for future experiments, it might become better.
Here is a code for add reduction (16 x fp32 vector).
The current one (using MultiDimReductionOp):
```
vxorps  %xmm0, %xmm0, %xmm0
vaddss  (%rdi), %xmm0, %xmm0
vaddss  4(%rdi), %xmm0, %xmm0
vaddss  8(%rdi), %xmm0, %xmm0
vaddss  12(%rdi), %xmm0, %xmm0
vaddss  16(%rdi), %xmm0, %xmm0
vaddss  20(%rdi), %xmm0, %xmm0
vaddss  24(%rdi), %xmm0, %xmm0
vaddss  28(%rdi), %xmm0, %xmm0
vaddss …
```
=> Add an option to choose between default reduction lowering and our own.

python/src/ir.cc, python/test/unit/language/test_compile_errors.py, python/test/unit/language/test_conversions.py, python/test/unit/language/test_core.py, third_party/cpu/backend/compiler.py, third_party/cpu/lib/TritonCPUTransforms/DecomposeFpConversions.cpp
This commit adds list of supported dtypes on CPU for test_fp8_support
from test_compile_errors.py suit. Also in upstream in ir.cc updated
get_fp8e4nv_ty and currently returns "Float8E4M3FNType" instead of "Float8E4M3FNUZType".
So I am updating corresponding conversions to use similar type.
=> [FP8 support] Enable Float8 tests failed after rebase

third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonToTritonCPU/Passes.h, third_party/cpu/include/TritonToTritonCPU/Passes.td, third_party/cpu/lib/TritonToTritonCPU/ConvertReductionOp.cpp, third_party/cpu/triton_cpu.cc
This is a PR to use `vector.reduction` for 1-D vectors when lowering `tt.reduce`.
Currently, `triton::ReduceOp` is lowered in a generic way with half shuffled and accumulated. However, some architecture support dedicated reduction instructions (e.g. `vredsum` in RVV), which cannot be inst-selected from current shuffle & accumulate pattern, and sub-optimal code might be generated. The 1-D reduction can be lowered later for specific target in the Target TTCIR stage, or just converted to intrinsics and let LLVM do the code generation.
An alternate approach is keeping the `mapToMultiDimReductionOp` enabled by default, and let the multi-reduction be converted to `llvm.vector.reduce.*` intrinsics for 1-D vectors. But according to [the previous …
=> Use 1-D vector reduction op to convert reduce op

include/triton/Tools/LinearLayout.h, lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/FMA.cpp, lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Tools/LinearLayout.cpp, python/test/unit/language/test_core.py, python/triton/testing.py, python/tutorials/03-matrix-multiplication-cpu.py
A super dirty hacky implementation for `DotOperandEncodingAttr::toLinearLayout` to support dot operations, except for dot 3d.
The default Triton dot operator is implemented in [lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/FMA.cpp](https://github.com/triton-lang/triton-cpu/blob/ed82c339e5c9b9329d1ef3b3edea0d64e515f6ce/lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/FMA.cpp#L93), which is very straightforward: a typical tiled matmul using fmad. Super interestingly, this baseline implementation gives a 2-3x speedup over `vector::contract` on an old Skylake machine. A similar speedup was also found on a newer Zen CPU. It's just one data point.
Anyhow, I just want to make this PoC to be more complete for any future reference. A few more diffs will be coming. 
```
matmul-performance-fp32 …
```
=> [cpu-v2] Super hacky LinearLayout for DotOperandEncoding

bin/RegisterTritonDialects.h, include/triton/Dialect/TritonCPU/IR/TritonCPUOps.td, test/TritonCPU/convert-memory-ops.mlir, test/TritonCPU/scalarize-memory-ops.mlir, third_party/cpu/backend/compiler.py, third_party/cpu/include/CMakeLists.txt, third_party/cpu/include/ScalarizePass/CMakeLists.txt, third_party/cpu/include/ScalarizePass/ScalarizeInterface.h, third_party/cpu/include/ScalarizePass/ScalarizeInterface.td, third_party/cpu/include/ScalarizePass/ScalarizeInterfaceImpl.h, third_party/cpu/include/TritonToTritonCPU/Passes.h, third_party/cpu/include/TritonToTritonCPU/Passes.td, third_party/cpu/lib/TritonToTritonCPU/CMakeLists.txt, third_party/cpu/lib/TritonToTritonCPU/ConvertMemoryOps.cpp, third_party/cpu/lib/TritonToTritonCPU/ScalarizeInterface.cpp, third_party/cpu/lib/TritonToTritonCPU/ScalarizeUsingForOps.cpp, third_party/cpu/triton_cpu.cc
This commit reworks functionality introduced in PR #119.
The current approach decides to insert SCF cycles earlier - with TTC IR
and with tensors instead of vectors.
This allows the analysis to be separated by operation type and applied
via an external interface, avoiding changes to the original operations. (ScalarizeInterface)
The original scalarization logic is now separated and placed in ScalarizeUsingForOpPass.
This reduces the complexity of the ConvertMemoryOps pass.
Thus, the conversion is now separated from the transformation of TTC IR.
=> [Scalarization/Loops generation] Refactor and new pass/interfaces introduced

test/TritonCPU/convert-memory-ops.mlir, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonToTritonCPU/Passes.h, third_party/cpu/include/TritonToTritonCPU/Passes.td, third_party/cpu/lib/TritonToTritonCPU/ConvertMemoryOps.cpp, third_party/cpu/lib/TritonToTritonCPU/ScalarizeUsingForOps.cpp, third_party/cpu/triton_cpu.cc
This PR add `lowerToGather` and `lowerToScatter` for load and store conversion. Memory ops with the pointer computed from splat and addptr can be lowered with `vector.gather` or `vector.scatter`.
For architectures with scatter and gather support (like SVE and RVV), the code generated with this approach might be more efficient.
Two options are added to scalarization and memory op conversion to enable lowering with gather and scatter operations.
=> Lower memory ops with vector gather and scatter

bin/RegisterTritonDialects.h, test/TritonCPU/dot-to-amx.mlir, third_party/cpu/CMakeLists.txt, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonCPUTransforms/Passes.h, third_party/cpu/include/TritonCPUTransforms/Passes.td, third_party/cpu/lib/TritonCPUTransforms/CMakeLists.txt, third_party/cpu/lib/TritonCPUTransforms/ConvertDotToAMX.cpp, third_party/cpu/triton_cpu.cc
This patch introduces a new pass to lower matmul using AMX vector dialect ops. This implementation is not yet optimal, additional improvements will be added later to reduce number of memory operations.
I checked perf and it improves significantly, especially for single-threaded mode. We will need to find out why multi-threading doesn't provide us with perf scaling as for Torch.
Current perf for BF16:
```
M       N       K  TritonCPU 1   TritonCPU
0    256.0   256.0   256.0    17.225417  163.044681
1    384.0   384.0   384.0    18.119113  359.164016
2    512.0   512.0   512.0    19.739487  489.369781
3    640.0   640.0   640.0    20.426998  580.103837
4    768.0   768.0   768.0    20.955009  616.985397
5    896.0   896.0   896.0    21.052365  633.909627
6   1024.0  1024.0  1024.0 …
```
=> Introduce DotOp lowering to AMX

include/triton/Dialect/TritonCPU/IR/TritonCPUOps.td, include/triton/Dialect/TritonCPU/IR/TritonCPUTypes.td, lib/Dialect/TritonCPU/IR/Ops.cpp, python/triton/language/extra/cpu/libdevice.py, third_party/cpu/lib/TritonCPUToLLVM/MathToVecLib.cpp, third_party/cpu/lib/TritonToTritonCPU/ConvertElementwiseOps.cpp
This PR adds support for libdevice functions that don't map cleanly to a MathOp. We implement them using tt.extern_elementwise instead, indicating which Sleef function to use.
While tt.extern_elementwise contains fields for the library path and name, the CUDA backend ignores those fields as it always uses the NVIDIA's libdevice library. We take a similar approach here and assume all extern calls go to the Sleef library.
One difference though is that we need to select our Sleef function based on the number of elements of the vector, which is done by interpolating this number into the symbol name. To indicate where this interpolation should occur, I have made `%(numel)` into a special string value. This allows us to reuse tt.extern_elementwise without adding any extra attributes.
=> Implement more libdevice functions using extern_elementwise

third_party/cpu/triton_cpu.cc
Allows compilation to succeed even when the latest kernel headers aren't present
=> Fix compilation when ARCH_REQ_XCOMP_PERM isn't defined

third_party/cpu/include/ScalarizePass/CMakeLists.txt, third_party/cpu/lib/TritonToTritonCPU/CMakeLists.txt
Found this issue while working for intenal build. `ScalarizeInterfaceIncGen` shouldn't have the MLIR prefix.
`add_mlir_interface` is defined in [mlir/cmake/modules/AddMLIR.cmake](https://github.com/llvm/llvm-project/blob/0de8de1b8432f01adb0a7c6d2f1e3d4fd8c0c30c/mlir/cmake/modules/AddMLIR.cmake#L191-L197). Drop the `MLIR` prefix, and no need to add dependency to `mlir-generic-headers`.
=> [NFC][CPU] Drop MLIR prefix in ScalarizeInterface

third_party/cpu/lib/TritonCPUToLLVM/MathToVecLib.cpp
Popping the null char inserted by the `snprintf` function. Leaving it causes CI issues.
=> Fix trailing null char in ulpSuffix

python/test/unit/runtime/test_autotuner.py
This commit skips test for non-cuda devices that exects to use_cuda_graph.
=> [Test][Autotuner] Skip use_cuda_graph for non cuda devices

python/tutorials/01-vector-add.py, python/tutorials/02-fused-softmax-cpu.py, python/tutorials/03-matrix-multiplication-cpu.py, python/tutorials/matrix-vector-multiplication-bf16.py, python/tutorials/matrix-vector-multiplication.py, third_party/cpu/backend/compiler.py, third_party/cpu/backend/driver.py
I propose to use a new kernel option instead of environment variables. `OMP_NUM_THREADS` variable still can be used though. This provides more explicit interface and matches GPU way to control parallelism. I'm also counting on autotuning it in the future.
=> Add num_threads option to control threading per kernel invocation.

include/triton/Dialect/TritonCPU/IR/TritonCPUOps.td, third_party/cpu/lib/TritonCPUToLLVM/DebugOpsToLLVM.cpp, third_party/cpu/lib/TritonToTritonCPU/ConvertDebugOps.cpp, third_party/cpu/runtime/cpu_runtime.cpp
This commit adds Memref type to possible inputs of print.
Memref have strides and other supporting information to
allow print multidimensional tensors. (2d, 3d etc)
Such print will be added in the next pr.
=> [TTC Print Memref] Simplify further multidimensional tensor printing

python/triton/runtime/autotuner.py, python/tutorials/01-vector-add.py, third_party/cpu/backend/driver.py
This patch adds `num_threads` tuning to autotuner and enables hooks timing by default for autotuner on CPU. It also adds an example of an autotuned vector-add kernel to the tutorial. Autotuned kernel can select proper configs for small vectors and be as efficient as manually tuned `add_tiled_with_st_threshold`.
=> Small fixes for autotuner on CPU

python/src/llvm.cc, python/triton/runtime/build.py, third_party/cpu/backend/compiler.py, third_party/cpu/backend/driver.py
Tested on vanilla macbook setup with the following
```
DISABLE_OPENMP=1 \
CC=$(which clang) \
TRITON_CPU_BACKEND=1 \
$(which python3) \
python/tutorials/01-vector-add.py
```
=> Small fixes for clang + macosx

third_party/cpu/runtime/cpu_runtime.cpp
This patch adds recursion to existing printer to handle N-dim tensors. Example kernel:
```
@triton.jit
def kernel_print(a):
a_block_ptr = tl.make_block_ptr(base=a, shape=(2, 2, 2, 16), strides=(64, 32, 16, 1), offsets=(0, 0, 0, 0),
block_shape=(2, 2, 2, 16), order=(3, 2, 1, 0))
tl.device_print("1d", tl.load(a + tl.arange(0, 16)))
tl.device_print("2d", tl.load(a_block_ptr).reshape(8, 16))
tl.device_print("4d", tl.load(a_block_ptr))
a = torch.randn((2, 2, 2, 16), dtype=torch.float32, device=device)
kernel_print[(1,)](a)
```
Output:
```
(0, 0, 0) 1d: [-0.5524, -0.4098, -1.7870,  0.2918, -1.1225, -0.0241,  0.0628,  0.2458,
-0.5359,  0.3338, -0.3889, -0.9465,  3.1933,  0.9299,  0.3630,  0.4745]
(0, 0, 0) 2d: [[-0.5524, -0.4098, -1.7870,  0.2918, -1.1225, -0.0241,  0.0628,  0.2458,
-0.5359, …
```
=> Support multi-dimensional tensor prints in CPU runtime.

third_party/cpu/triton_cpu.cc
Summary: Follow the https://github.com/triton-lang/triton-cpu/pull/165 example, and update one macro for building on linux-aarch64.
=> Fix linux-aarch64 build

python/test/unit/runtime/test_subproc.py
on MacOS spawn is the default, not fork.
=> Handle platform dependent start method

python/triton/runtime/build.py
Tested as,
```
OMP_NUM_THREADS=8                                          \
TRITON_LOCAL_LIBOMP_PATH="<path..to>/site-packages/torch/" \
CC=$(which clang)                                          \
TRITON_CPU_BACKEND=1                                       \
$(which python3)                                           \
python/tutorials/02-fused-softmax-cpu.py
```
=> Allow using local omp with Apple clang

third_party/cpu/lib/TritonCPUToLLVM/DebugOpsToLLVM.cpp, third_party/cpu/lib/TritonToTritonCPU/ConvertDebugOps.cpp, third_party/cpu/runtime/cpu_runtime.cpp
Easy fix and update.
Added float16 support for PrintOp.
Interestingly, negative numbers were incorrectly printed. The unittest, `test_print[device_print_negative-int32]`, was failing. Why did't CI catch it? Anyhow quickly fixed it.
---
Testing
- Now all print unit tests are passed.
- float16 testing:
```
> % TRITON_CPU_BACKEND=1 python3 python/test/unit/language/print_helper.py test_print device_print_negative float16 cpu
Unsupported bitWidth
UNREACHABLE executed at /data/users/minjang/triton-oss/triton-cpu-minjang/third_party/cpu/runtime/cpu_runtime.cpp:251!
> % TRITON_CPU_BACKEND=1 python3 python/test/unit/language/print_helper.py test_print device_print_negative float16 cpu
(0, 0, 0) x: [   -0.0000,   -1.0000,   -2.0000,   -3.0000,   -4.0000,   -5.0000,   -6.0000,   -7.0000,
-8.0000, …
```
=> Fix isSigned and add float16 in PrintOp

test/TritonCPU/canonicalize.mlir, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonCPUTransforms/Passes.h, third_party/cpu/include/TritonCPUTransforms/Passes.td, third_party/cpu/lib/TritonCPUTransforms/CMakeLists.txt, third_party/cpu/lib/TritonCPUTransforms/Canonicalize.cpp, third_party/cpu/triton_cpu.cc
This patch adds a canonicalizer pass to be used on TTCIR. Its goal is to simplify pattern matching in transformation passes. So far, it has a single pattern only to fold shape cast into transfer read. This simplifies code analysis for multidimensional block pointers (e.g. for blocked layout matmul where I use 4D block pointers to load 2D blocks).
=> Add TritonCPU canonicalizer.

python/tutorials/03-matrix-multiplication-cpu.py, python/tutorials/cpu-blocked-matmul-fp32.py, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonCPUTransforms/Passes.h, third_party/cpu/include/TritonCPUTransforms/Passes.td, third_party/cpu/lib/TritonCPUTransforms/CMakeLists.txt, third_party/cpu/lib/TritonCPUTransforms/ConvertDotOp/ConvertDotCommon.cpp, third_party/cpu/lib/TritonCPUTransforms/ConvertDotOp/ConvertDotCommon.h, third_party/cpu/lib/TritonCPUTransforms/ConvertDotOp/ConvertDotToFMA.cpp, third_party/cpu/triton_cpu.cc
This PR adds lowering for DotOp through vector FMA and broadcast operations. The lowering is quite simple and doesn't work well for all block sizes, so a block size fitting register file is preferred. It provides much better performance compared to the contraction operation lowering.
The patch also adds some fixes to the matmul tutorial to provide more measuring options. First, it utilizes block pointers to improve analysis and simplify code generation. Second, it introduces a padding feature to improve caching by avoiding power of two strides.
Here are the performance results for the current lowering through vector contraction op:
```
matmul-performance-torch.float32 (CACHE_PADDING=False PREPACKED=False PAD_B_ONLY=True GROUP_SIZE_M=8):
M       N       K  TritonCPU 1   TritonCPU  TorchCPU …
```
=> Introduce FMA lowering for DotOp.

python/tutorials/03-matrix-multiplication-cpu.py, python/tutorials/cpu-blocked-matmul-fp32.py, third_party/cpu/include/TritonCPUTransforms/OptCommon.h, third_party/cpu/lib/TritonCPUTransforms/ConvertDotOp/ConvertDotToAMX.cpp
Initial AMX lowering was constrained by limitations in LLVM that forced suboptimal code generation. With all those problems fixed, AMX code generation can be improved. Mostly, improvements avoid unnecessary data copies in memory and tile spills/fills. 
Here are the current matmul results:
```
matmul-performance-torch.bfloat16 (USE_BLOCK_POINTERS=True CACHE_PADDING=False PREPACKED=False PAD_B_ONLY=True GROUP_SIZE_M=8):
M       N       K  TritonCPU 1     TritonCPU  TorchCPU (native)
0    256.0   256.0   256.0   195.246945    869.475833         302.701015
1    384.0   384.0   384.0   244.640081   2029.952337         794.682071
2    512.0   512.0   512.0   276.182932   2750.447317        1544.400887
3    640.0   640.0   640.0   301.045105   3350.790461        2272.750134
4    768.0   768.0 …
```
=> AMX lowering improvements

python/tutorials/03-matrix-multiplication-cpu.py
Avoid extra store when block pointers are used in the 03 tutorial for CPU.
=> Fix extra-store in matmul tutorial.

third_party/cpu/include/TritonCPUTransforms/OptCommon.h
This patch removes useless bounds checks enabled by default for read/write operations emitted for AMX lowering. It doesn't improve performance (most checks can be statically removed anyway) but makes the resulting code cleaner.
=> Remove unnecessary bounds checks.

third_party/cpu/lib/TritonCPUToLLVM/DebugOpsToLLVM.cpp
=> Fix isSigned usage for scalar prints.

python/tutorials/cpu-blocked-matmul.py, test/TritonCPU/dot-to-amx.mlir, third_party/cpu/language/cpu/__init__.py, third_party/cpu/language/cpu/utils.py, third_party/cpu/lib/TritonCPUTransforms/ConvertDotOp/ConvertDotCommon.cpp, third_party/cpu/lib/TritonCPUTransforms/ConvertDotOp/ConvertDotCommon.h, third_party/cpu/lib/TritonCPUTransforms/ConvertDotOp/ConvertDotToAMX.cpp, third_party/cpu/lib/TritonToTritonCPU/ConvertElemManipOps.cpp
This patch allows the use of AMX lowering for input that is preliminary VNNI encoded to have an ability do directly load input data to AMX tile registers for RHS. To enable such a scheme without changes in the front-end, I use VNNI decoding sequence in a kernel right before tl.dot. AMX lowering pass then detects this sequence and uses encoded data instead of emitting a code to VNNI encode RHS. For more convenient usage, the required sequence is available as a function in `tl.extra.cpu`.
Blocked matmul tutorial was modified to support FP16, BF16, and INT8 inputs with optional VNNI packing during the layout change. Enabled VNNI encoding provide nice performance improvement:
```
M       N       K  triton-cpu-bb-tb-pb-prepack-bfloat16 triton-cpu-bb-tb-prepack-bfloat16 …
```
=> Support VNNI pre-encoded input in AMX lowering.

python/src/llvm.cc
First try to lookup the Target in the given module. If it doesn't work, use the default target. And set it in the module.
Rationale: Issue #207
=> Update default target selection logic

third_party/cpu/backend/driver.py
Fixes https://github.com/triton-lang/triton-cpu/issues/204. It is now possible to import triton, execute a kernel, and autotune, all without torch.
Relatively straightforward translation of `torch.tensor` -> `np.array`, `torch.float` -> `np.float32`, `np.quantile` -> `torch.quantile` (note the default method for both is `linear`), and so on. Luckily numpy has `np.min`, `np.max`, `np.mean`, `np.median`, and `np.all` with the same semantics as the respective torch functions, so the same `getattr(np, return_mode)(times)` trick can be used.
I was getting
```
ImportError: ~/.triton/cache/TMED6KFKLZGWOEVFFCXVTCPBLE/__triton_cpu_launcher.so: undefined symbol: omp_get_thread_num
```
which was fixed either by importing torch or by adding `omp` to `libraries` in the cpu driver, …
=> [RUNTIME] Reduce runtime dependency on torch

include/triton/Dialect/TritonCPU/IR/TritonCPUOps.td, python/tutorials/cpu-blocked-matmul.py, test/TritonCPU/dot-to-xsmm.mlir, third_party/cpu/CMakeLists.txt, third_party/cpu/backend/compiler.py, third_party/cpu/include/TritonCPUToLLVM/Passes.h, third_party/cpu/include/TritonCPUToLLVM/Passes.td, third_party/cpu/include/TritonCPUTransforms/Passes.h, third_party/cpu/include/TritonCPUTransforms/Passes.td, third_party/cpu/lib/TritonCPUToLLVM/CMakeLists.txt, third_party/cpu/lib/TritonCPUToLLVM/UkernelOpsToXSMMLLVM.cpp, third_party/cpu/lib/TritonCPUTransforms/ConvertDotOp/ConvertDotOpToUkernelOps.cpp, third_party/cpu/runtime/runtime_xsmm.cpp, third_party/cpu/triton_cpu.cc
Adds libxsmm as a new XSMM ukernel target for CPU lowering.
Initial lowering covers basic support for FP32 and BF16 data types across different extensions and architectures.
Summary of changes:
- Extends ukernel handle creator to allow reuse for both backends
- Adds prebuilt libxsmm as an optional external build dependency
- Adds XSMM runtime and lowering pass
=> [XSMM] libxsmm ukernel backend
