python/src/ir.cc
python/test/unit/cpu/test_libdevice.py
python/triton/language/extra/cpu/__init__.py
python/triton/language/extra/cpu/libdevice.py
python/triton/language/extra/libdevice.py
third_party/cpu/backend/compiler.py
third_party/cpu/lib/TritonToTritonCPU/ConvertElementwiseOps.cpp

This patch adds libdevice support for CPU. For now, it's just a basic set of math functions.

Add libdevice for CPU.

---

python/test/unit/language/test_core.py
third_party/cpu/lib/TritonCPUToLLVM/FuncOpToLLVM.cpp

Fix FuncOp lowering.

---

third_party/cpu/lib/TritonToTritonCPU/ConvertElementwiseOps.cpp

This makes most of the int32 tests in test_random.py pass. (int64 ones are still failing.)
Fixes https://github.com/triton-lang/triton-cpu/issues/62.

[cpu] Have MulhiUI lowering support scalars

---

python/test/unit/language/test_core.py

Our pre-commit hook is failing

[cpu] Fix formatting

---

.github/workflows/build-test.yml
third_party/cpu/lib/TritonToTritonCPU/ConvertMemoryOps.cpp

This makes test_block_pointer.py pass.
Fixes #60.

[cpu] Support tl.load(..., padding="nan")

---

third_party/cpu/include/TritonCPUTransforms/OptCommon.h
third_party/cpu/lib/TritonCPUTransforms/ConvertUnsupportedOps.cpp
third_party/cpu/lib/TritonCPUTransforms/DecomposeFpConversions.cpp
third_party/cpu/lib/TritonToTritonCPU/ConvertElementwiseOps.cpp

Per https://github.com/triton-lang/triton-cpu/pull/64#issuecomment-2245758319

[cpu] Use helpers from OptCommon.h to simplify code

---

third_party/cpu/lib/TritonToTritonCPU/ConvertMemoryOps.cpp

* Address comments on #69 
* Properly handle case where `padding_option` is not specified (we should default to zero. No test for it exists, I will upstream one shortly)

[cpu] Follow up to #69

---

third_party/cpu/lib/TritonToTritonCPU/ConvertElementwiseOps.cpp
third_party/cpu/lib/TritonToTritonCPU/ConvertPtrOps.cpp

Two changes:
1. Lower mulhiui to mulhi_extended rather than a bunch of ext / trunc instructions. This greatly simplifies the code, as well as automatically gets it working for 64-bit inputs, which the previous implementation did not handle correctly
2. Only emit extsi if the result bitwidth is larger than the input bitwidth. Otherwise it fails validation.
This gets the int64 tests in test_random.py passing.
Fixes https://github.com/triton-lang/triton-cpu/issues/71.

[cpu] Get more of test_random.py working

---

python/test/unit/language/test_block_pointer.py
python/test/unit/language/test_core.py
third_party/cpu/lib/TritonCPUTransforms/ConvertUnsupportedOps.cpp

This should make our CI runs much more reliable. Let's see if it helps to pass CI for this PR.

Reduce/disable some tests on CPU for faster CI runs.

---

python/test/unit/cpu/test_opt.py
third_party/cpu/lib/TritonCPUTransforms/OptimizeMasks.cpp

Fix optimization bug identified in https://github.com/triton-lang/triton-cpu/pull/96#discussion_r1708170874

Fix incorrect casts in mask optimization.

---

python/test/unit/language/test_core.py
third_party/cpu/lib/TritonToTritonCPU/ConvertControlFlowOps.cpp

& add a test that covers the case where the loop's arguments are tensors, not just scalars

Add conversion for scf.while

---

python/tutorials/04-low-memory-dropout.py
python/tutorials/05-layer-norm.py
python/tutorials/07-extern-functions.py

Enable three tutorials by using the active driver backend name for the device.

Enable few more tutorials for CPU

---

include/triton/Dialect/TritonCPU/IR/TritonCPUOps.td
python/test/unit/language/print_helper.py
python/test/unit/language/test_subprocess.py
third_party/cpu/lib/TritonCPUToLLVM/DebugOpsToLLVM.cpp
third_party/cpu/lib/TritonToTritonCPU/ConvertDebugOps.cpp
third_party/cpu/runtime/cpu_runtime.cpp

Okay, finally dumping the old testing code. Later we will support multi-dimensional cases. I was trying to keep the original testing code for GPU. And meanwhile, the upstream luckily fixed signed issue. Incorporated the latest print semantic.

[CPU] Add unit test for print with isSigned and several fixes

---

python/test/unit/cpu/test_math.py
third_party/cpu/lib/TritonCPUToLLVM/MathToVecLib.cpp

This PR is stacked on top of #136.

Vectorize expm1, sqrt, and floor using sleef

---

python/tutorials/01-vector-add.py
third_party/cpu/runtime/cpu_runtime.cpp

Addressing https://github.com/triton-lang/triton-cpu/issues/143

Use llvm_unreachable in cpu_runtime.cpp

---

third_party/cpu/CMakeLists.txt

Really sorry that I didn't missed the link error.

Fix undefined symbol error in libTritonCPURuntime.so

---

python/test/unit/cpu/test_math.py
third_party/cpu/lib/TritonCPUToLLVM/MathToVecLib.cpp

libsleef does not implement 2-element functions, so for libdevice functions implemented via extern_elementwise ops that rely wholly on libsleef implementations (as opposed to MathOps which can be lowered to native instructions), we need to pad those vectors to size 4.
This allows us to enable test_math.py for all the functions introduced in https://github.com/triton-lang/triton-cpu/pull/161.

Pad size 2 vectors to size 4 when lowering extern_elementwise ops

---

python/src/llvm.cc
python/test/unit/cpu/test_math.py
third_party/cpu/backend/compiler.py
third_party/cpu/include/TritonCPUToLLVM/Passes.h
third_party/cpu/lib/TritonCPUToLLVM/MathToVecLib.cpp
third_party/cpu/triton_cpu.cc

WIP - will update summary later

Fix math tests for armv8

---

third_party/cpu/runtime/cpu_runtime.cpp
third_party/cpu/runtime/runtime_onednn.cpp

This commits adds missing headers to runtime files.
Resolves: #180

Add missing headers toruntime

---

python/triton/testing.py

This commit reverts drawing changes introduced in PR #197.

[NFC] Revert drawing changes

---

third_party/cpu/triton_cpu.cc

Simplifies lowering VectorToLLVM options and setting OuterProduct for TransformsOptions to allow pass arm tests.

[VectorLowering] Reduce amount of opts for ARM

---

third_party/cpu/backend/driver.py

This reverts commit 9d8154c1ff8f59ec2ccd76c4ea91f38c6b7b18db.
Discovered new issues with using approach, that was proposed in #205 .
How to check:
```diff
diff --git a/python/triton/compiler/compiler.py b/python/triton/compiler/compiler.py
index 772b76d1e..6bdf9ee47 100644
--- a/python/triton/compiler/compiler.py
+++ b/python/triton/compiler/compiler.py
@@ -359,6 +359,7 @@ class CompiledKernel:
launch_enter_hook = None
launch_exit_hook = None
+    num_compiled_kernels = 0
def __init__(self, src, metadata_group, hash):
from collections import namedtuple
@@ -404,6 +405,9 @@ class CompiledKernel:
max_tmem_size = 512  # tmem size in number of columns
if self.metadata.tmem_size > max_tmem_size:
raise OutOfResources(self.metadata.tmem_size, max_tmem_size, "tensor memory")
+        # if …
```

Revert "[RUNTIME] Reduce runtime dependency on torch (#205)"
